on:
  push:
name: action
jobs:
  hello-world:
    name: Un job para saludar
    runs-on: ubuntu-latest
    steps:
      - name: Step Hola Mundo
        id: hello
        uses: saqpsaqp/helloworld-githubactions@v1
        with:
          who-to-greet: "Mundo Pewito"
      - name: Usar el Output
        run: echo "la fecha fue ${{ steps.hello.outputs.time }}"
